services:
#    vl_platform.example:
#        class: VL\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    vl_platform.antispam:
        class: VL\PlatformBundle\Antispam\VLAntispam